### PR TITLE
Add enum to lib.rs

### PR DESCRIPTION
**Pull request by lidarbtc**
Add Proxy enum to lib.rs.
for use Proxy enum match.

### CODE REVIEW

**Comment by marirs** [comment]
Hi - Whats the difference between the changed file and the existing? or was it just a `cargo fmt` change?
I see the same between the patch and the old one?

**Comment by lidarbtc** [comment]
Only add "record::Proxy" to lib.rs.
It is possible that I misunderstood.
I mean if it changed user can use "Proxy" enum with match.

```rs
let record = record.is_proxy;

match record {
    Proxy::IsAProxy => println("proxy");
    Proxy::IsNotAProxy => println("not proxy");
}
```

**Comment by marirs** [comment]
Ahh got it!!

**Comment by marirs** [comment]
Ok - merged and also published to crates!
Thanks for the contribution :)

**Pull request merged**
